services:
  database:
    container_name: "postgres-dev-customer-control"
    image: postgres:16.0-alpine3.18
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
    volumes:
      - customer-control_data:/var/lib/postgresql/data

volumes:
  customer-control_data:
